name: med_alert
description: "Facilitando a vida das pessoas idosas"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  camera: ^0.10.1+1

  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^0.8.4+10
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png